# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

dockers:
  - image_templates:
      ["ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="For various clients for subscriptions"
      - --label=org.opencontainers.image.url=https://github.com/christianarty/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/christianarty/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      ["ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="For various clients for subscriptions"
      - --label=org.opencontainers.image.url=https://github.com/christianarty/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/christianarty/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
docker_manifests:
  - name_template: ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/christianarty/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/christianarty/{{ .ProjectName }}:{{ .Version }}-arm64v8
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
